EXECUTE BLOCK RETURNS (
  clicodigo INTEGER,
  gclcodigo INTEGER,
  chave VARCHAR(50),
  qtd INTEGER,
  procodigo VARCHAR(50)
) AS
DECLARE VARIABLE v_clicodigo INTEGER;
DECLARE VARIABLE v_gclcodigo INTEGER;
DECLARE VARIABLE v_chave VARCHAR(50);
DECLARE VARIABLE v_qtd INTEGER;
DECLARE VARIABLE v_procodigo VARCHAR(50);
BEGIN
  FOR
    WITH CLI AS (
      SELECT DISTINCT 
        C.CLICODIGO,
        CLINOMEFANT,
        ENDCODIGO,
        GCLCODIGO
      FROM CLIEN C
      INNER JOIN (
        SELECT 
          CLICODIGO,
          E.ZOCODIGO,
          ENDCODIGO 
        FROM ENDCLI E
        INNER JOIN (
          SELECT ZOCODIGO 
          FROM ZONA 
          WHERE ZOCODIGO IN (20)
        ) Z ON E.ZOCODIGO = Z.ZOCODIGO 
        WHERE ENDFAT = 'S'
      ) A ON C.CLICODIGO = A.CLICODIGO 
      WHERE CLICLIENTE = 'S'
    ),
    FIS AS (
      SELECT FISCODIGO 
      FROM TBFIS 
      WHERE FISTPNATOP IN ('V', 'R', 'SR')
    ),
    PED AS (
      SELECT 
        ID_PEDIDO,
        PEDDTEMIS,
        P.CLICODIGO,
        GCLCODIGO,
        CLINOMEFANT
      FROM PEDID P
      INNER JOIN CLI C ON P.CLICODIGO = C.CLICODIGO AND P.ENDCODIGO = C.ENDCODIGO
      WHERE PEDDTEMIS BETWEEN DATEADD(-180 DAY TO CURRENT_DATE) AND 'YESTERDAY' 
      AND PEDSITPED <> 'C'
    ),
    PROD_LEN AS (
      SELECT 
        PROCODIGO,
        IIF(PROCODIGO2 IS NULL, PROCODIGO, PROCODIGO2) CHAVE 
      FROM PRODU 
      WHERE MARCODIGO IN (57, 24)
    ),
    MAIN_RESULTS AS (
      SELECT 
        P.CLICODIGO,
        P.GCLCODIGO,
        PR.CHAVE,
        SUM(PD.PDPQTDADE) AS QTD,
        (SELECT FIRST 1 PD1.PROCODIGO
         FROM PDPRD PD1
         INNER JOIN PRODU PR1 ON PD1.PROCODIGO = PR1.PROCODIGO
         WHERE PD1.ID_PEDIDO = PD.ID_PEDIDO AND PR1.PROTIPO = 'T'
         ORDER BY PD1.ID_PEDIDO, PD1.PROCODIGO) AS PROCODIGO
      FROM PDPRD PD
      INNER JOIN PED P ON PD.ID_PEDIDO = P.ID_PEDIDO
      INNER JOIN FIS F ON PD.FISCODIGO = F.FISCODIGO
      INNER JOIN PROD_LEN PR ON PD.PROCODIGO = PR.PROCODIGO
      GROUP BY P.CLICODIGO, P.GCLCODIGO, PR.CHAVE, PD.ID_PEDIDO
    )
    SELECT 
      CLICODIGO,
      GCLCODIGO,
      CHAVE,
      SUM(QTD) AS QTD,
      PROCODIGO
    FROM MAIN_RESULTS
    GROUP BY CLICODIGO, GCLCODIGO, CHAVE, PROCODIGO
  INTO :v_clicodigo, :v_gclcodigo, :v_chave, :v_qtd, :v_procodigo
  DO
  BEGIN
    -- Emit combined results
    clicodigo = :v_clicodigo;
    gclcodigo = :v_gclcodigo;
    chave = :v_chave;
    qtd = :v_qtd;
    procodigo = :v_procodigo;
    SUSPEND;
  END
END;
